---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/kind --version
    register: kind_test_output
  - name: kind --version
    debug:
      msg: '{{ kind_test_output.stdout }}'
